/**
 * Export utilities for voice recordings and enriched notes
 */

export interface ExportMetadata {
  timestamp: string;
  language: string;
  enrichmentMode: string;
  duration?: number;
}

export interface ExportData {
  transcription: string;
  enrichedResult: string;
  metadata: ExportMetadata;
}

/**
 * Generate markdown content from export data
 */
export function generateMarkdown(data: ExportData): string {
  const { transcription, enrichedResult, metadata } = data;

  const markdown = `# Voice Intelligence Note

**Date:** ${metadata.timestamp}
**Language:** ${metadata.language}
**Enrichment Mode:** ${metadata.enrichmentMode}
${metadata.duration ? `**Duration:** ${formatDuration(metadata.duration)}` : ''}

---

## Original Transcription

${transcription}

---

## Enriched Result

${enrichedResult}

---

*Generated by Voice Intelligence Assistant*
`;

  return markdown;
}

/**
 * Copy text to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    } else {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = text;
      textArea.style.position = 'fixed';
      textArea.style.left = '-999999px';
      document.body.appendChild(textArea);
      textArea.focus();
      textArea.select();
      const success = document.execCommand('copy');
      document.body.removeChild(textArea);
      return success;
    }
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Download markdown file
 */
export function downloadMarkdown(content: string, filename: string): void {
  try {
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';

    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Failed to download markdown:', error);
    throw error;
  }
}

/**
 * Generate filename with timestamp
 */
export function generateFilename(prefix = 'note'): string {
  const now = new Date();
  const timestamp = now.toISOString().replace(/[:.]/g, '-').slice(0, -5);
  return `${prefix}_${timestamp}.md`;
}

/**
 * Format duration in seconds to readable string
 */
export function formatDuration(seconds: number): string {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  const parts = [];
  if (hours > 0) parts.push(`${hours}h`);
  if (minutes > 0) parts.push(`${minutes}m`);
  if (secs > 0) parts.push(`${secs}s`);

  return parts.join(' ') || '0s';
}

/**
 * Get current timestamp in readable format
 */
export function getCurrentTimestamp(): string {
  const now = new Date();
  return now.toLocaleString('de-DE', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  });
}
