import React, { useState } from 'react';
import { trpc } from '@/lib/trpc';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Loader2, Trash2, Star, Download, Copy } from 'lucide-react';
import { toast } from 'sonner';
import { useTranslation } from 'react-i18next';
import { copyToClipboard, downloadMarkdown, generateFilename } from '@/lib/exportUtils';

export function RecordingHistory() {
  const { t } = useTranslation();
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedRecording, setSelectedRecording] = useState<number | null>(null);

  // Queries
  const { data: historyData, isLoading, refetch } = trpc.history.list.useQuery({
    limit: 50,
    offset: 0,
  });

  // Mutations
  const deleteRecording = trpc.history.delete.useMutation();
  const toggleFavorite = trpc.history.toggleFavorite.useMutation();
  const updateRecording = trpc.history.update.useMutation();

  const handleDelete = async (id: number) => {
    if (!confirm(t('history.confirmDelete') || 'Are you sure?')) return;

    try {
      await deleteRecording.mutateAsync({ id });
      toast.success(t('history.messages.deleted'));
      refetch();
    } catch (error) {
      const message = error instanceof Error ? error.message : t('common.error');
      toast.error(message);
    }
  };

  const handleToggleFavorite = async (id: number, isFavorite: boolean) => {
    try {
      await toggleFavorite.mutateAsync({ id, isFavorite: !isFavorite });
      toast.success(t('history.messages.favoriteUpdated'));
      refetch();
    } catch (error) {
      const message = error instanceof Error ? error.message : t('common.error');
      toast.error(message);
    }
  };

  const handleCopy = async (text: string) => {
    try {
      const success = await copyToClipboard(text);
      if (success) {
        toast.success(t('recorder.messages.copiedToClipboard'));
      }
    } catch (error) {
      toast.error(t('common.error'));
    }
  };

  const handleExport = (recording: any) => {
    const markdown = `# Voice Recording Note

**Date:** ${new Date(recording.createdAt).toLocaleString()}
**Language:** ${recording.transcriptionLanguage}
**Mode:** ${recording.enrichmentMode || 'N/A'}
**Duration:** ${recording.duration ? `${Math.floor(recording.duration / 60)}:${String(recording.duration % 60).padStart(2, '0')}` : 'N/A'}

## Transcription

${recording.transcription}

${
  recording.enrichedResult
    ? `## Enriched Result

${recording.enrichedResult}`
    : ''
}

${recording.notes ? `## Notes

${recording.notes}` : ''}

---

*Generated by Voice Intelligence Assistant*
`;

    downloadMarkdown(markdown, generateFilename('recording'));
    toast.success(t('history.messages.exported'));
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-8">
        <Loader2 className="w-6 h-6 animate-spin text-blue-500" />
      </div>
    );
  }

  const recordings = historyData?.recordings || [];

  return (
    <div className="w-full space-y-6">
      {/* Header */}
      <div>
        <h2 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">
          {t('history.title')}
        </h2>
        <Input
          type="text"
          placeholder={t('history.searchPlaceholder')}
          value={searchQuery}
          onChange={(e) => setSearchQuery(e.target.value)}
          className="bg-white dark:bg-slate-700 text-slate-900 dark:text-white border border-slate-300 dark:border-slate-600"
        />
      </div>

      {/* Empty State */}
      {recordings.length === 0 ? (
        <Card className="p-12 text-center bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
          <p className="text-slate-600 dark:text-slate-400">{t('history.empty')}</p>
        </Card>
      ) : (
        /* Recordings List */
        <div className="space-y-3">
          {recordings
            .filter(
              (r) =>
                r.transcription.toLowerCase().includes(searchQuery.toLowerCase()) ||
                (r.title && r.title.toLowerCase().includes(searchQuery.toLowerCase()))
            )
            .map((recording) => (
              <Card
                key={recording.id}
                className="p-4 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:shadow-md transition-shadow cursor-pointer"
                onClick={() => setSelectedRecording(selectedRecording === recording.id ? null : recording.id)}
              >
                {/* Recording Header */}
                <div className="flex items-start justify-between mb-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="font-semibold text-slate-900 dark:text-white">
                        {recording.title || `Recording ${recording.id}`}
                      </h3>
                      {recording.isFavorite && (
                        <Star className="w-4 h-4 fill-yellow-400 text-yellow-400" />
                      )}
                    </div>
                    <p className="text-xs text-slate-600 dark:text-slate-400">
                      {new Date(recording.createdAt).toLocaleString()}
                    </p>
                  </div>

                  {/* Actions */}
                  <div className="flex gap-2">
                    <Button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleToggleFavorite(recording.id, recording.isFavorite);
                      }}
                      variant="ghost"
                      size="sm"
                      className="text-slate-600 dark:text-slate-400 hover:text-yellow-500"
                    >
                      <Star
                        className={`w-4 h-4 ${recording.isFavorite ? 'fill-yellow-400' : ''}`}
                      />
                    </Button>
                    <Button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleExport(recording);
                      }}
                      variant="ghost"
                      size="sm"
                      className="text-slate-600 dark:text-slate-400 hover:text-blue-500"
                    >
                      <Download className="w-4 h-4" />
                    </Button>
                    <Button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleCopy(recording.enrichedResult || recording.transcription);
                      }}
                      variant="ghost"
                      size="sm"
                      className="text-slate-600 dark:text-slate-400 hover:text-green-500"
                    >
                      <Copy className="w-4 h-4" />
                    </Button>
                    <Button
                      onClick={(e) => {
                        e.stopPropagation();
                        handleDelete(recording.id);
                      }}
                      variant="ghost"
                      size="sm"
                      className="text-slate-600 dark:text-slate-400 hover:text-red-500"
                      disabled={deleteRecording.isPending}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                </div>

                {/* Metadata */}
                <div className="grid grid-cols-4 gap-2 mb-3 text-xs">
                  <div className="bg-slate-50 dark:bg-slate-700/50 p-2 rounded">
                    <p className="text-slate-600 dark:text-slate-400">Language</p>
                    <p className="font-semibold text-slate-900 dark:text-white">
                      {recording.transcriptionLanguage}
                    </p>
                  </div>
                  <div className="bg-slate-50 dark:bg-slate-700/50 p-2 rounded">
                    <p className="text-slate-600 dark:text-slate-400">Mode</p>
                    <p className="font-semibold text-slate-900 dark:text-white capitalize">
                      {recording.enrichmentMode || 'N/A'}
                    </p>
                  </div>
                  <div className="bg-slate-50 dark:bg-slate-700/50 p-2 rounded">
                    <p className="text-slate-600 dark:text-slate-400">Duration</p>
                    <p className="font-semibold text-slate-900 dark:text-white">
                      {recording.duration
                        ? `${Math.floor(recording.duration / 60)}:${String(recording.duration % 60).padStart(2, '0')}`
                        : 'N/A'}
                    </p>
                  </div>
                  <div className="bg-slate-50 dark:bg-slate-700/50 p-2 rounded">
                    <p className="text-slate-600 dark:text-slate-400">Enriched</p>
                    <p className="font-semibold text-slate-900 dark:text-white">
                      {recording.enrichedResult ? 'Yes' : 'No'}
                    </p>
                  </div>
                </div>

                {/* Expanded Content */}
                {selectedRecording === recording.id && (
                  <div className="border-t border-slate-200 dark:border-slate-700 pt-4 space-y-4">
                    <div>
                      <p className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                        Transcription
                      </p>
                      <p className="text-sm text-slate-700 dark:text-slate-300 max-h-32 overflow-y-auto">
                        {recording.transcription}
                      </p>
                    </div>

                    {recording.enrichedResult && (
                      <div>
                        <p className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                          Enriched Result
                        </p>
                        <p className="text-sm text-slate-700 dark:text-slate-300 max-h-32 overflow-y-auto">
                          {recording.enrichedResult}
                        </p>
                      </div>
                    )}

                    {recording.notes && (
                      <div>
                        <p className="text-sm font-semibold text-slate-700 dark:text-slate-300 mb-2">
                          Notes
                        </p>
                        <p className="text-sm text-slate-700 dark:text-slate-300">
                          {recording.notes}
                        </p>
                      </div>
                    )}
                  </div>
                )}
              </Card>
            ))}
        </div>
      )}
    </div>
  );
}
